### ISSUE TITLE
Error running slicer_wiki_extensions_module_listings.py on windows

### ISSUE THREAD

**Issue by johan-andruejol** [Slicer/slicer-wiki-scripts#7]
Find stack trace here:

```
johan@Hogwarts MINGW64 /d/Slicer/Slicer-B/Slicer-build
$ /d/Slicer/Slicer-B/Slicer-build/Slicer.exe --launch /c/Python27/python.exe /d/Slicer/wiki-scripts/slicer_wiki_extension_module_listing.py update-wiki --test-wiki-update /d/Slicer/Slicer-B/Slicer-build// /d/Slicer/extensions_dir/

pip install mwclient==0.6.5

Starting D:/Slicer/Slicer-B/Slicer-build/Slicer.exe --launch \
  pip.exe \
  install \
  mwclient==0.6.5

Downloading 'https://bootstrap.pypa.io/get-pip.py' into 'get-pip.py'

Installing pip

Starting D:/Slicer/Slicer-B/Slicer-build/Slicer.exe --launch \
  python.exe \
  get-pip.py

pip install mwclient==0.6.5

Starting D:/Slicer/Slicer-B/Slicer-build/Slicer.exe --launch \
  pip.exe \
  install \
  mwclient==0.6.5
Traceback (most recent call last):
  File "D:/Slicer/wiki-scripts/slicer_wiki_extension_module_listing.py", line 1722, in <module>
    args.action(args)
  File "D:/Slicer/wiki-scripts/slicer_wiki_extension_module_listing.py", line 1626, in _updateWiki
    slicerVersion=args.slicer_version)
  File "D:/Slicer/wiki-scripts/slicer_wiki_extension_module_listing.py", line 1320, in updateWiki
    runPip(['install', 'mwclient==0.6.5'], slicerBuildDir=slicerBuildDir)
  File "D:/Slicer/wiki-scripts/slicer_wiki_extension_module_listing.py", line 838, in runPip
    _runPip()
  File "D:/Slicer/wiki-scripts/slicer_wiki_extension_module_listing.py", line 833, in _runPip
    slicerLauncherPopen(getSlicerLauncher(slicerBuildDir), ['--launch', _e('pip')] + args)
  File "D:/Slicer/wiki-scripts/slicer_wiki_extension_module_listing.py", line 850, in slicerLauncherPopen
    raise RuntimeError, "Calling {0} failed (exit code {1})".format(launcher, ec)
RuntimeError: Calling D:/Slicer/Slicer-B/Slicer-build/Slicer.exe failed (exit code 1)
```

**Comment by jcfr** [comment]
Thanks for the report.

Few things:
- Look like you are providing you own python interprecter .. could you try to simply use `python.exe`. This will correspond to the one build by Slicer (automatically found in the path already set by the launcher).
- Does the same happen if you run the command from a regular windows command line ?
- correct syntax is posted here: https://github.com/Slicer/DashboardScripts/blob/master/factory-south-ubuntu-slicer-update-wiki.sh

It means your command would look like this:

```
d:\Slicer\Slicer-B\Slicer-build\Slicer.exe --launch python.exe D:\Slicer\wiki-scripts\slicer_wiki_extension_module_listing.py update-wiki --test-wiki-update D:\Slicer\Slicer-B\Slicer-build\ WIKI_PASSWORD
```

**Comment by johan-andruejol** [comment]
- I had the same error when using just python.exe

I'll try the others.
